# Generated by Django 6.0.4 on 2026-05-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('medidor_id', models.CharField(max_length=50, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.suscriptor')),
            ],
        ),
    ]
