# Generated by Django 6.0.4 on 2026-05-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lectura_options_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
