# Generated by Django 6.0.4 on 2026-06-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_suscriptor_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_m3', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Tarifa por m³')),
                ('cargo_aseo', models.DecimalField(decimal_places=2, default=7000, max_digits=10, verbose_name='Cargo de aseo')),
                ('cargo_reconexion', models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Cargo de reconexión')),
                ('dias_plazo_pago', models.PositiveIntegerField(default=15, verbose_name='Días de plazo para pago')),
                ('nombre_empresa', models.CharField(default='EMPRESA DE SERVICIOS PÚBLICOS AAA CORPOSINAÍ', max_length=255, verbose_name='Nombre de la empresa')),
                ('nit_empresa', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('direccion_empresa', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mensaje_pie', models.TextField(blank=True, default='Paga a tiempo tu factura y no te expongas al cobro por reconexión.', verbose_name='Mensaje al pie')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='abono_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono a la deuda'),
        ),
        migrations.AddField(
            model_name='factura',
            name='deuda_acumulada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deuda acumulada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email enviado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='firma_cobrador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firma cobrador'),
        ),
        migrations.AddField(
            model_name='factura',
            name='nuevo_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nuevo saldo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subsidio_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T. Pagado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_aseo',
            field=models.DecimalField(decimal_places=2, default=7000, max_digits=10, verbose_name='Cargo aseo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_consumo_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor consumo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_m3',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Valor m³'),
        ),
        migrations.AddField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.factura'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=20, verbose_name='N° Recibo'),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='codigo_usuario',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código de usuario'),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Documento de identidad'),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='subsidio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio aplicado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='abonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abonos'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='consumo',
            field=models.FloatField(default=0, verbose_name='Consumo m³'),
        ),
    ]
