# Generated by Django 6.0.4 on 2026-06-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_configuraciongeneral_factura_abono_deuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='api.periodolectura'),
        ),
    ]
