# Generated by Django 6.0.4 on 2026-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_m3', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Tarifa por m³')),
                ('cargo_aseo', models.DecimalField(decimal_places=2, default=7000, max_digits=10, verbose_name='Cargo de aseo')),
                ('cargo_reconexion', models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Cargo de reconexión')),
                ('dias_plazo_pago', models.PositiveIntegerField(default=15, verbose_name='Días de plazo para pago')),
                ('nombre_empresa', models.CharField(default='EMPRESA DE SERVICIOS PÚBLICOS AAA CORPOSINAÍ', max_length=255, verbose_name='Nombre de la empresa')),
                ('nit_empresa', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('direccion_empresa', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('mensaje_pie', models.TextField(blank=True, default='Paga a tiempo tu factura y no te expongas al cobro por reconexión.', verbose_name='Mensaje al pie')),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
                'db_table': 'api_configuraciongeneral',
            },
        ),
    ]
