# Generated by Django 6.0.4 on 2026-06-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('suscriptores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('PAGO', 'Pago Total'), ('ABONO', 'Abono')], default='PAGO', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('numero_recibo', models.CharField(blank=True, max_length=20, verbose_name='N° Recibo')),
                ('comentario', models.TextField(blank=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturas.factura')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscriptores.suscriptor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'api_pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
