# Generated by Django 6.0.4 on 2026-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('medidor_id', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Correo electrónico')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Documento de identidad')),
                ('codigo_usuario', models.CharField(blank=True, max_length=20, verbose_name='Código de usuario')),
                ('subsidio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio aplicado')),
                ('estado_servicio', models.CharField(choices=[('ACTIVO', 'Activo'), ('CORTADO', 'Cortado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('mes_deuda_continua', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'db_table': 'api_suscriptor',
                'ordering': ['nombre'],
            },
        ),
    ]
