# Generated by Django 6.0.4 on 2026-06-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
        ('suscriptores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Factura')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo', models.FloatField(default=0, verbose_name='Consumo m³')),
                ('valor_m3', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Valor m³')),
                ('valor_aseo', models.DecimalField(decimal_places=2, default=7000, max_digits=10, verbose_name='Cargo aseo')),
                ('valor_consumo_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor consumo')),
                ('subsidio_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subsidio')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('deuda_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deuda acumulada')),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abonos')),
                ('abono_deuda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono a la deuda')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('firma_cobrador', models.CharField(blank=True, max_length=100, verbose_name='Firma cobrador')),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='T. Pagado')),
                ('nuevo_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nuevo saldo')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='lecturas.periodolectura')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='suscriptores.suscriptor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'api_factura',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
