# Generated by Django 6.0.4 on 2026-06-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscriptores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Período de Lectura',
                'verbose_name_plural': 'Períodos de Lectura',
                'db_table': 'api_periodolectura',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('lecturista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_tomadas', to=settings.AUTH_USER_MODEL)),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='suscriptores.suscriptor')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='lecturas.periodolectura')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'api_lectura',
                'ordering': ['-fecha_lectura'],
            },
        ),
    ]
